### ISSUE TITLE
Deployment Process

### ISSUE THREAD

**Issue by TanukiKabuki** [roscoe81/enviro-monitor#10]
I am new to all this so bare with me. After following the Enviro+ setup, how do you then go through and utilize the config.json file in the setup? I have a raspberry pi that I have managed to get connected with the enviro plus and I can get it to activate but looking at your documentation and reading through I would like to utilize it though I am unsure how to go about doing so.

**Comment by roscoe81** [comment]
You need to set up your own config.json file and store it in the location specified by replacing <Your config.json file location> in line 80 of the code (for example, you could use home/pi/configs/config.json). The instructions on how to set up the variables in your own config.json are [here](https://github.com/roscoe81/enviro-monitor/blob/master/Config/Config_README.md) and the you can use [this](https://github.com/roscoe81/enviro-monitor/blob/master/Config/config.json) as the foundation. Let me know if that helps.
