### ISSUE TITLE
[Question] PPM readings vs other recommendation guides

### ISSUE THREAD

**Issue by DR-DinoMight** [roscoe81/enviro-monitor#15]
Hi

First of all, thank you for this.

Secondly, this is my first project like this of sorts, so you're repo, has really helped me understand how to use the Envrio+, outside of the examples, but I'm just wondering if you could explain a little bit more about the numbers, please?

I'm trying to make an indoor air quality sensor that I can use to keep tabs on my office, nothing super accurate, just something to let me know when changes are needed with the air quality, temp and humidity, so I'm trying to extend your code so that I can output overall quality regarding the factors mentioned, but when I come to work out the levels for the cO2 I see my reading are as followed in the json file

```
{"Time": "Sunday 06 February 2022 @ 10:29:01", "Run Time": 39005.0, "Raw Temperature": 35.84, "Output Temp": 24.21, "Raw Humidity": 17.07, "Output Humidity": 28.9, "Output Bar": 993.4, "Raw Bar": 972.4, "Oxi": 0.16, "Red": 3.31, "NH3": 0.89, "Raw OxiRS": 17448.0, "Raw RedRS": 310803.0, "Raw NH3RS": 66298.0}
```

and I know that the `Red` output is the one I'm looking for cO2  but when I compare that with some guidance of recommended cO2 PPM they don't correlate?

![image](https://user-images.githubusercontent.com/1541665/152677466-6d4610f8-f1b3-493e-9123-ac772ac1f784.png)
[Taken from here](https://www.co2meter.com/blogs/news/monitor-indoor-air-quality-at-home)

Is there a table you used to work out good/bad ranges? Are your numbers shortened? or am I just completely getting the wrong end of the stick? (more likely 😅 ).

Many thanks for the help in advance!

**Comment by DR-DinoMight** [comment]
I have just realised that I could be completely getting the wrong end of the stick regarding RED and cO2 (ie not the same) so sorry if any of this just isn't making sense! 

Ultimlatily  just trying to find good ranges for Air quality 😅

**Comment by roscoe81** [comment]
You're correct @DR-DinoMight, RED and CO2 are different. You could try the option of adding the SGP30 sensor that my code supports. It measures VOC and eCO2 (equivalent CO2) and I've found it useful for measuring indoor air quality.
