### ISSUE TITLE
Your Watchdog File Name Here

### ISSUE THREAD

**Issue by iancattermole** [roscoe81/enviro-monitor#16]
Hi, really want to use this but being a novice I'm a little lost. I can work my way around most issues but struggling with this one

For now I'm using the default json file /home/pi/enviro-monitor/Config/config.json
Searching for watchdog but a little lost -- may be beyond my level at the moment

Raspberry Pi Zero W Buster, Enviro+

Appreciate your time & efforts
Regards, Ian

pi@tas:~/enviro-monitor $ python3 Northcliff_AQI_Monitor_Gen.py
2022-11-16 10:59:37.556 INFO     Northcliff_Environment_Monitor.py - Pimoroni Enviro+ with noise measurement (and optional SGP30) sensor capture and display.
 Supports external sensor capture and Luftdaten, mqtt and Adafruit IO Updates
 Disclaimer: The noise measurement is not to be used for accurate sound level measurements.

#Note: you'll need to register with Luftdaten at:
#https://meine.luftdaten.info/ and enter your Raspberry Pi
#serial number that's displayed on the Enviro plus LCD along
#with the other details before the data appears on the
#Luftdaten map.

#
6.11 - Gen
Retrieved Config {'version': 'Base-6.10a', 'temp_offset': 0, 'altitude': 23, 'enable_display': True, 'enable_adafruit_io': False, 'aio_user_name': '<>', 'aio_key': '<>', 'aio_feed_window': 0, 'aio_feed_sequence': 0, 'aio_household_prefix': '<>', 'aio_location_prefix': '<>', 'aio_package': '<>', 'enable_send_data_to_homemanager': False, 'enable_receive_data_from_homemanager': False, 'enable_indoor_outdoor_functionality': False, 'outdoor_source_type': '<>', 'outdoor_source_id': {}, 'enable_noise': False, 'mqtt_broker_name': '<>', 'mqtt_username': '', 'mqtt_password': '', 'enable_luftdaten': False, 'enable_luftdaten_noise': False, 'disable_luftdaten_sensor_upload': 'None', 'enable_climate_and_gas_logging': False, 'enable_particle_sensor': True, 'enable_eco2_tvoc': False, 'gas_daily_r0_calibration_hour': 3, 'reset_gas_sensor_calibration': False, 'incoming_temp_hum_mqtt_topic': '<>', 'incoming_temp_hum_mqtt_sensor_name': '<>', 'incoming_barometer_mqtt_topic': '<>', 'incoming_barometer_sensor_id': 0, 'indoor_outdoor_function': 'Outdoor', 'mqtt_client_name': '<>', 'outdoor_mqtt_topic': '<>', 'indoor_mqtt_topic': '<>', 'city_name': 'Sydney', 'time_zone': 'Australia/Sydney', 'custom_locations': ['Townsville, Australia, Queensland, -19.26639, 146.80569', 'Thredbo, Australia, Sydney, -36.4999989, 148.2999988', 'Romsey, Australia, Victoria, -37.3581082, 144.7365582']}
2022-11-16 10:59:39.843 INFO     Raspberry Pi serial: 0000000000000000
2022-11-16 10:59:39.857 INFO     Wi-Fi: connected

Startup R0. Red R0: 9328.0 Oxi R0: 3327.0 NH3 R0: 2416.0
No Mender Software Version Available. Using Default
No Mender Config Version Available. Using Default
No Persistent Data Log Available. Using Defaults
Invalid Persistent Data Log. Using Defaults
Internal Temp/Hum Sensor
Internal Barometer
Raw Bar: 989.6 Comp Bar: 992.3
Reading Raw Gas sensors before warmup completed
Red Rs: 133867.0 Oxi Rs: 2333.0 NH3 Rs: 4032.0
Luftdaten Values {'P2': '822', 'P1': '1077', 'temperature': '17.93', 'humidity': '74.66', 'pressure': '98962.31'}
mqtt Values {'Gas Calibrated': False, 'Bar': [992.3, '0'], 'Hum': [74.7, '1'], 'Forecast': {'Valid': False, '3 Hour Change': 0, 'Forecast': 'Insufficient Data'}, 'P2.5': 822, 'P10': 1077, 'P1': 298, 'Temp': 17.9, 'Min Temp': None, 'Max Temp': None, 'Red': 0.16, 'Oxi': 0.11, 'NH3': 0.27, 'Lux': 11.0}
Traceback (most recent call last):
  File "Northcliff_AQI_Monitor_Gen.py", line 2289, in <module>
    with open('<Your Watchdog File Name Here>', 'w') as f:
PermissionError: [Errno 13] Permission denied: '<Your Watchdog File Name Here>'
pi@tas:~/enviro-monitor $ ^C

**Comment by roscoe81** [comment]
You need to replace any text beginning with a < and ending in a > with your own text. For example you could replace <Your Watchdog File Name Here> with something like /home/pi/watchdog_folder/watchdog.log
