### ISSUE TITLE
adafruit.io has updated package offerings

### ISSUE THREAD

**Issue by jnofsinger** [roscoe81/enviro-monitor#17]
commenting here to note that adafruit.io now offers 10 free streams and anything else is considered adafruit.io+ that gives you access to 60 streams for $10.00 a month or $99.00 a year.

the current Basic or Basic air scripts get you 5 or 5 streams and the preminium gets you 14 which no longer fits the free tiers.  10 isn't optimal with the PM gauge, so I ended up having to mark my license as premium and remove extra items like lux and weather to get what I wanted.  

Ultimately some of the code should be refactored to allow the additional free streams.  I might take a crack at this if I have some time along with changing metrics to barbarian freedom units since I live in the US

**Comment by roscoe81** [comment]
Thanks for the feedback and I'm glad that you were able to customise the code to suit your particular needs. As a clarification, the premium configs never fitted into Adafruit IO's free package and always required Adafruit IO+. I chose 5 feeds for the Basic packages to allow two monitors (e.g. indoor and outdoor) to share a free Adafruit IO account and stay within the 10 feed limit. Also note that Adafruit IO+ has an unlimited number of feeds but has a limit of 60 data points per minute.
