### ISSUE TITLE
Case

### ISSUE THREAD

**Issue by boatsheds** [roscoe81/enviro-monitor#2]
Hello,

A couple of queries please.
Is there any chance of getting a picture of the assembled case?
What is the recommended plastic for construction?

Thanks
Hugh

**Comment by roscoe81** [comment]
I used PLA. It’s not perfect but it does the job. Here are some shots and let me know if you need any further information 
![21ACE1B9-B09D-4A56-A4E7-F3D2D2604E15](https://user-images.githubusercontent.com/37389643/78981314-01c6b580-7b63-11ea-9b1f-f4dea0a9136c.jpeg)
![3A177E54-25CE-4C28-99C5-9ADB999172C7](https://user-images.githubusercontent.com/37389643/78981321-07bc9680-7b63-11ea-9ee4-486208a23778.jpeg)
![E7A6AB34-5E5A-4EC4-9BF9-4F7FD5CF87DB](https://user-images.githubusercontent.com/37389643/78981327-09865a00-7b63-11ea-80c2-764dc42b67ac.jpeg)

**Comment by roscoe81** [comment]
..and showing the particle sensor
![A89F6DC6-4A67-4778-A7B6-F7DF39D6F250](https://user-images.githubusercontent.com/37389643/78981845-2e2f0180-7b64-11ea-9a8c-996be4d984b9.jpeg)

**Comment by boatsheds** [comment]
Ross,

Thanks, that is a great help.
best regards
Hugh
