### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by jeffrayjones** [roscoe81/enviro-monitor#8]
Hi roscoe81,

just tried to run your program. 
Getting an error message. ...line 1205 SyntaxError: Non-ASCII character ˋ\xc2ˋ...on line 1205, but no encoding declared
Maybe I did something wrong. I’m pretty new at raspbian.

Thanks a lot

**Comment by roscoe81** [comment]
That looks similar to Issue #5 that was solved by using Python3. Are you using Python3?

**Comment by jeffrayjones** [comment]
That's exactly it. Sorry. Thanks very much

**Comment by roscoe81** [comment]
No problem @jeffrayjones, glad I could help.
