### ISSUE TITLE
Positive Feedback: This really works well.

### ISSUE THREAD

**Issue by Extra-Fox** [roscoe81/enviro-monitor#9]
Just wanted to let you know that I really enjoyed getting this working. It took a bit what with my limited understanding of electronics and code, but once I got it running it's been stable and reliable the whole time.

I even built a custom enclosure to hold all the bits in a tidy little space: https://www.prusaprinters.org/prints/51359-pimoroni-enviro-super-deluxe-indoor-air-quality-ho

**Comment by roscoe81** [comment]
Thanks for the feedback @Extra-Fox, I really appreciate it. I spent a long time on stability and reliability, so it's great to hear that it paid off. I also love your custom enclosure, it's very creative!
